// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"bitbucket.org/almatoag/bardioc-go/graph"
	"bitbucket.org/almatoag/bardioc-go/graph/esquery"
	"bitbucket.org/almatoag/bardioc-go/graph/gremlin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEdgeClient creates a new instance of MockEdgeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEdgeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEdgeClient {
	mock := &MockEdgeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEdgeClient is an autogenerated mock type for the EdgeClient type
type MockEdgeClient struct {
	mock.Mock
}

type MockEdgeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEdgeClient) EXPECT() *MockEdgeClient_Expecter {
	return &MockEdgeClient_Expecter{mock: &_m.Mock}
}

// CreateEntity provides a mock function for the type MockEdgeClient
func (_mock *MockEdgeClient) CreateEntity(ctx context.Context, n graph.Node, p ...graph.Param) graph.Row {
	var tmpRet mock.Arguments
	if len(p) > 0 {
		tmpRet = _mock.Called(ctx, n, p)
	} else {
		tmpRet = _mock.Called(ctx, n)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateEntity")
	}

	var r0 graph.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, graph.Node, ...graph.Param) graph.Row); ok {
		r0 = returnFunc(ctx, n, p...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Row)
		}
	}
	return r0
}

// MockEdgeClient_CreateEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEntity'
type MockEdgeClient_CreateEntity_Call struct {
	*mock.Call
}

// CreateEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - n graph.Node
//   - p ...graph.Param
func (_e *MockEdgeClient_Expecter) CreateEntity(ctx interface{}, n interface{}, p ...interface{}) *MockEdgeClient_CreateEntity_Call {
	return &MockEdgeClient_CreateEntity_Call{Call: _e.mock.On("CreateEntity",
		append([]interface{}{ctx, n}, p...)...)}
}

func (_c *MockEdgeClient_CreateEntity_Call) Run(run func(ctx context.Context, n graph.Node, p ...graph.Param)) *MockEdgeClient_CreateEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 graph.Node
		if args[1] != nil {
			arg1 = args[1].(graph.Node)
		}
		var arg2 []graph.Param
		var variadicArgs []graph.Param
		if len(args) > 2 {
			variadicArgs = args[2].([]graph.Param)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEdgeClient_CreateEntity_Call) Return(row graph.Row) *MockEdgeClient_CreateEntity_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockEdgeClient_CreateEntity_Call) RunAndReturn(run func(ctx context.Context, n graph.Node, p ...graph.Param) graph.Row) *MockEdgeClient_CreateEntity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntity provides a mock function for the type MockEdgeClient
func (_mock *MockEdgeClient) DeleteEntity(ctx context.Context, id graph.MetadataID, p ...graph.Param) graph.Row {
	var tmpRet mock.Arguments
	if len(p) > 0 {
		tmpRet = _mock.Called(ctx, id, p)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntity")
	}

	var r0 graph.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, graph.MetadataID, ...graph.Param) graph.Row); ok {
		r0 = returnFunc(ctx, id, p...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Row)
		}
	}
	return r0
}

// MockEdgeClient_DeleteEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntity'
type MockEdgeClient_DeleteEntity_Call struct {
	*mock.Call
}

// DeleteEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - id graph.MetadataID
//   - p ...graph.Param
func (_e *MockEdgeClient_Expecter) DeleteEntity(ctx interface{}, id interface{}, p ...interface{}) *MockEdgeClient_DeleteEntity_Call {
	return &MockEdgeClient_DeleteEntity_Call{Call: _e.mock.On("DeleteEntity",
		append([]interface{}{ctx, id}, p...)...)}
}

func (_c *MockEdgeClient_DeleteEntity_Call) Run(run func(ctx context.Context, id graph.MetadataID, p ...graph.Param)) *MockEdgeClient_DeleteEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 graph.MetadataID
		if args[1] != nil {
			arg1 = args[1].(graph.MetadataID)
		}
		var arg2 []graph.Param
		var variadicArgs []graph.Param
		if len(args) > 2 {
			variadicArgs = args[2].([]graph.Param)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEdgeClient_DeleteEntity_Call) Return(row graph.Row) *MockEdgeClient_DeleteEntity_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockEdgeClient_DeleteEntity_Call) RunAndReturn(run func(ctx context.Context, id graph.MetadataID, p ...graph.Param) graph.Row) *MockEdgeClient_DeleteEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntitiesByXID provides a mock function for the type MockEdgeClient
func (_mock *MockEdgeClient) GetEntitiesByXID(ctx context.Context, externalID string, p ...graph.Param) (graph.Rows, error) {
	var tmpRet mock.Arguments
	if len(p) > 0 {
		tmpRet = _mock.Called(ctx, externalID, p)
	} else {
		tmpRet = _mock.Called(ctx, externalID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetEntitiesByXID")
	}

	var r0 graph.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...graph.Param) (graph.Rows, error)); ok {
		return returnFunc(ctx, externalID, p...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...graph.Param) graph.Rows); ok {
		r0 = returnFunc(ctx, externalID, p...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...graph.Param) error); ok {
		r1 = returnFunc(ctx, externalID, p...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEdgeClient_GetEntitiesByXID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntitiesByXID'
type MockEdgeClient_GetEntitiesByXID_Call struct {
	*mock.Call
}

// GetEntitiesByXID is a helper method to define mock.On call
//   - ctx context.Context
//   - externalID string
//   - p ...graph.Param
func (_e *MockEdgeClient_Expecter) GetEntitiesByXID(ctx interface{}, externalID interface{}, p ...interface{}) *MockEdgeClient_GetEntitiesByXID_Call {
	return &MockEdgeClient_GetEntitiesByXID_Call{Call: _e.mock.On("GetEntitiesByXID",
		append([]interface{}{ctx, externalID}, p...)...)}
}

func (_c *MockEdgeClient_GetEntitiesByXID_Call) Run(run func(ctx context.Context, externalID string, p ...graph.Param)) *MockEdgeClient_GetEntitiesByXID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []graph.Param
		var variadicArgs []graph.Param
		if len(args) > 2 {
			variadicArgs = args[2].([]graph.Param)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEdgeClient_GetEntitiesByXID_Call) Return(rows graph.Rows, err error) *MockEdgeClient_GetEntitiesByXID_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockEdgeClient_GetEntitiesByXID_Call) RunAndReturn(run func(ctx context.Context, externalID string, p ...graph.Param) (graph.Rows, error)) *MockEdgeClient_GetEntitiesByXID_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntity provides a mock function for the type MockEdgeClient
func (_mock *MockEdgeClient) GetEntity(ctx context.Context, id graph.MetadataID, p ...graph.Param) graph.Row {
	var tmpRet mock.Arguments
	if len(p) > 0 {
		tmpRet = _mock.Called(ctx, id, p)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetEntity")
	}

	var r0 graph.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, graph.MetadataID, ...graph.Param) graph.Row); ok {
		r0 = returnFunc(ctx, id, p...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Row)
		}
	}
	return r0
}

// MockEdgeClient_GetEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntity'
type MockEdgeClient_GetEntity_Call struct {
	*mock.Call
}

// GetEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - id graph.MetadataID
//   - p ...graph.Param
func (_e *MockEdgeClient_Expecter) GetEntity(ctx interface{}, id interface{}, p ...interface{}) *MockEdgeClient_GetEntity_Call {
	return &MockEdgeClient_GetEntity_Call{Call: _e.mock.On("GetEntity",
		append([]interface{}{ctx, id}, p...)...)}
}

func (_c *MockEdgeClient_GetEntity_Call) Run(run func(ctx context.Context, id graph.MetadataID, p ...graph.Param)) *MockEdgeClient_GetEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 graph.MetadataID
		if args[1] != nil {
			arg1 = args[1].(graph.MetadataID)
		}
		var arg2 []graph.Param
		var variadicArgs []graph.Param
		if len(args) > 2 {
			variadicArgs = args[2].([]graph.Param)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEdgeClient_GetEntity_Call) Return(row graph.Row) *MockEdgeClient_GetEntity_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockEdgeClient_GetEntity_Call) RunAndReturn(run func(ctx context.Context, id graph.MetadataID, p ...graph.Param) graph.Row) *MockEdgeClient_GetEntity_Call {
	_c.Call.Return(run)
	return _c
}

// QueryGremlin provides a mock function for the type MockEdgeClient
func (_mock *MockEdgeClient) QueryGremlin(ctx context.Context, builder *gremlin.Builder, rootID graph.MetadataID, p ...graph.Param) (graph.Rows, error) {
	var tmpRet mock.Arguments
	if len(p) > 0 {
		tmpRet = _mock.Called(ctx, builder, rootID, p)
	} else {
		tmpRet = _mock.Called(ctx, builder, rootID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryGremlin")
	}

	var r0 graph.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gremlin.Builder, graph.MetadataID, ...graph.Param) (graph.Rows, error)); ok {
		return returnFunc(ctx, builder, rootID, p...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *gremlin.Builder, graph.MetadataID, ...graph.Param) graph.Rows); ok {
		r0 = returnFunc(ctx, builder, rootID, p...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *gremlin.Builder, graph.MetadataID, ...graph.Param) error); ok {
		r1 = returnFunc(ctx, builder, rootID, p...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEdgeClient_QueryGremlin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryGremlin'
type MockEdgeClient_QueryGremlin_Call struct {
	*mock.Call
}

// QueryGremlin is a helper method to define mock.On call
//   - ctx context.Context
//   - builder *gremlin.Builder
//   - rootID graph.MetadataID
//   - p ...graph.Param
func (_e *MockEdgeClient_Expecter) QueryGremlin(ctx interface{}, builder interface{}, rootID interface{}, p ...interface{}) *MockEdgeClient_QueryGremlin_Call {
	return &MockEdgeClient_QueryGremlin_Call{Call: _e.mock.On("QueryGremlin",
		append([]interface{}{ctx, builder, rootID}, p...)...)}
}

func (_c *MockEdgeClient_QueryGremlin_Call) Run(run func(ctx context.Context, builder *gremlin.Builder, rootID graph.MetadataID, p ...graph.Param)) *MockEdgeClient_QueryGremlin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *gremlin.Builder
		if args[1] != nil {
			arg1 = args[1].(*gremlin.Builder)
		}
		var arg2 graph.MetadataID
		if args[2] != nil {
			arg2 = args[2].(graph.MetadataID)
		}
		var arg3 []graph.Param
		var variadicArgs []graph.Param
		if len(args) > 3 {
			variadicArgs = args[3].([]graph.Param)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockEdgeClient_QueryGremlin_Call) Return(rows graph.Rows, err error) *MockEdgeClient_QueryGremlin_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockEdgeClient_QueryGremlin_Call) RunAndReturn(run func(ctx context.Context, builder *gremlin.Builder, rootID graph.MetadataID, p ...graph.Param) (graph.Rows, error)) *MockEdgeClient_QueryGremlin_Call {
	_c.Call.Return(run)
	return _c
}

// QueryVertices provides a mock function for the type MockEdgeClient
func (_mock *MockEdgeClient) QueryVertices(ctx context.Context, builder *esquery.Builder, p ...graph.Param) (graph.Rows, error) {
	var tmpRet mock.Arguments
	if len(p) > 0 {
		tmpRet = _mock.Called(ctx, builder, p)
	} else {
		tmpRet = _mock.Called(ctx, builder)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryVertices")
	}

	var r0 graph.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *esquery.Builder, ...graph.Param) (graph.Rows, error)); ok {
		return returnFunc(ctx, builder, p...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *esquery.Builder, ...graph.Param) graph.Rows); ok {
		r0 = returnFunc(ctx, builder, p...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *esquery.Builder, ...graph.Param) error); ok {
		r1 = returnFunc(ctx, builder, p...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEdgeClient_QueryVertices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryVertices'
type MockEdgeClient_QueryVertices_Call struct {
	*mock.Call
}

// QueryVertices is a helper method to define mock.On call
//   - ctx context.Context
//   - builder *esquery.Builder
//   - p ...graph.Param
func (_e *MockEdgeClient_Expecter) QueryVertices(ctx interface{}, builder interface{}, p ...interface{}) *MockEdgeClient_QueryVertices_Call {
	return &MockEdgeClient_QueryVertices_Call{Call: _e.mock.On("QueryVertices",
		append([]interface{}{ctx, builder}, p...)...)}
}

func (_c *MockEdgeClient_QueryVertices_Call) Run(run func(ctx context.Context, builder *esquery.Builder, p ...graph.Param)) *MockEdgeClient_QueryVertices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *esquery.Builder
		if args[1] != nil {
			arg1 = args[1].(*esquery.Builder)
		}
		var arg2 []graph.Param
		var variadicArgs []graph.Param
		if len(args) > 2 {
			variadicArgs = args[2].([]graph.Param)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEdgeClient_QueryVertices_Call) Return(rows graph.Rows, err error) *MockEdgeClient_QueryVertices_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *MockEdgeClient_QueryVertices_Call) RunAndReturn(run func(ctx context.Context, builder *esquery.Builder, p ...graph.Param) (graph.Rows, error)) *MockEdgeClient_QueryVertices_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntity provides a mock function for the type MockEdgeClient
func (_mock *MockEdgeClient) UpdateEntity(ctx context.Context, n graph.Node, p ...graph.Param) graph.Row {
	var tmpRet mock.Arguments
	if len(p) > 0 {
		tmpRet = _mock.Called(ctx, n, p)
	} else {
		tmpRet = _mock.Called(ctx, n)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateEntity")
	}

	var r0 graph.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, graph.Node, ...graph.Param) graph.Row); ok {
		r0 = returnFunc(ctx, n, p...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(graph.Row)
		}
	}
	return r0
}

// MockEdgeClient_UpdateEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntity'
type MockEdgeClient_UpdateEntity_Call struct {
	*mock.Call
}

// UpdateEntity is a helper method to define mock.On call
//   - ctx context.Context
//   - n graph.Node
//   - p ...graph.Param
func (_e *MockEdgeClient_Expecter) UpdateEntity(ctx interface{}, n interface{}, p ...interface{}) *MockEdgeClient_UpdateEntity_Call {
	return &MockEdgeClient_UpdateEntity_Call{Call: _e.mock.On("UpdateEntity",
		append([]interface{}{ctx, n}, p...)...)}
}

func (_c *MockEdgeClient_UpdateEntity_Call) Run(run func(ctx context.Context, n graph.Node, p ...graph.Param)) *MockEdgeClient_UpdateEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 graph.Node
		if args[1] != nil {
			arg1 = args[1].(graph.Node)
		}
		var arg2 []graph.Param
		var variadicArgs []graph.Param
		if len(args) > 2 {
			variadicArgs = args[2].([]graph.Param)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEdgeClient_UpdateEntity_Call) Return(row graph.Row) *MockEdgeClient_UpdateEntity_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *MockEdgeClient_UpdateEntity_Call) RunAndReturn(run func(ctx context.Context, n graph.Node, p ...graph.Param) graph.Row) *MockEdgeClient_UpdateEntity_Call {
	_c.Call.Return(run)
	return _c
}
